
package com.proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CheckTokenWebService", targetNamespace = "http://webservice.txt.extractdata.report.jiuqi.com/", wsdlLocation = "http://extest.btg.com.cn:8088/dna_ws/ICheckTokenWebService?wsdl")
public class CheckTokenWebService
    extends Service
{

    private final static URL CHECKTOKENWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException CHECKTOKENWEBSERVICE_EXCEPTION;
    private final static QName CHECKTOKENWEBSERVICE_QNAME = new QName("http://webservice.txt.extractdata.report.jiuqi.com/", "CheckTokenWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://extest.btg.com.cn:8088/dna_ws/ICheckTokenWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHECKTOKENWEBSERVICE_WSDL_LOCATION = url;
        CHECKTOKENWEBSERVICE_EXCEPTION = e;
    }

    public CheckTokenWebService() {
        super(__getWsdlLocation(), CHECKTOKENWEBSERVICE_QNAME);
    }

    public CheckTokenWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHECKTOKENWEBSERVICE_QNAME, features);
    }

    public CheckTokenWebService(URL wsdlLocation) {
        super(wsdlLocation, CHECKTOKENWEBSERVICE_QNAME);
    }

    public CheckTokenWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHECKTOKENWEBSERVICE_QNAME, features);
    }

    public CheckTokenWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CheckTokenWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ICheckTokenWebService
     */
    @WebEndpoint(name = "ICheckTokenWebService")
    public ICheckTokenWebService getICheckTokenWebService() {
        return super.getPort(new QName("http://webservice.txt.extractdata.report.jiuqi.com/", "ICheckTokenWebService"), ICheckTokenWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICheckTokenWebService
     */
    @WebEndpoint(name = "ICheckTokenWebService")
    public ICheckTokenWebService getICheckTokenWebService(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.txt.extractdata.report.jiuqi.com/", "ICheckTokenWebService"), ICheckTokenWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHECKTOKENWEBSERVICE_EXCEPTION!= null) {
            throw CHECKTOKENWEBSERVICE_EXCEPTION;
        }
        return CHECKTOKENWEBSERVICE_WSDL_LOCATION;
    }

}
